@urlBase = http://localhost:3001

###GetAll 
{{urlBase}}/api/blogs

###GetByID
GET {{urlBase}}/api/blogs/687321b5b3e4c8a425f5c57c


###Create blog
POST {{urlBase}}/api/blogs
Accept: application/json
Content-Type: application/json

{
    "title": "Lolaso ",
    "author": "Nahu",
    "url": "www.rivxczr.com.ar",
    "likes": 111
}
###Create invalid blog
POST {{urlBase}}/api/blogs
Accept: application/json
Content-Type: application/json

{
    "author": "Nahu",
    "url": "www.rivxczr.com.ar",
    "likes": 11
}

###Delete blog
DELETE {{urlBase}}/api/blogs/688cf96bae5a443a28c0a61e