@urlBase = http://localhost:3001
@idUser = 68a785aafcee282f267989d0
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxvbGFzbyIsImlkIjoiNjhhNzg1YWFmY2VlMjgyZjI2Nzk4OWQwIiwiaWF0IjoxNzU2MzI0Njg3fQ.bli1EEyc7Ka9mme_sxpPnrEbYv3AUxDMjSxrN71IB1Q

###GetAll 
{{urlBase}}/api/blogs

###GetByID
GET {{urlBase}}/api/blogs/687321b5b3e4c8a425f5c57c


###Create blog
POST {{urlBase}}/api/blogs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "AgeOfEmpire",
    "author": "Nahu N",
    "url": "www.qweqweq.com.ar",
    "likes": 1321,
    "userId": "{{idUser}}"
}

###Create valid blog but with invalid token
POST {{urlBase}}/api/blogs
Accept: application/json
Content-Type: application/json
Authorization: Bearer asdas12312wqeasd12414

{
    "title": "AgeOfEmpire",
    "author": "Nahu N",
    "url": "www.qweqweq.com.ar",
    "likes": 1321,
    "userId": "{{idUser}}"
}

###Create invalid blog
POST {{urlBase}}/api/blogs
Accept: application/json
Content-Type: application/json

{
    "author": "Nahu",
    "url": "www.rivxczr.com.ar",
    "likes": 11
}

###Delete blog
DELETE {{urlBase}}/api/blogs/68af5f8c3d1b097048aa0b07

###Update blog
PUT {{urlBase}}/api/blogs/687321b5b3e4c8a425f5c57c
Accept: application/json
Content-Type: application/json

{
    "likes": 1
}

###Update whithout blog
PUT {{urlBase}}/api/blogs/687321b5b3e4c8a425f5c57c
Accept: application/json
Content-Type: application/json

{

}