@urlBase = http://localhost:3001

###GetAll 
{{urlBase}}/api/blogs

###GetByID
GET {{urlBase}}/api/blogs/687321b5b3e4c8a425f5c57c


###Create blog
POST {{urlBase}}/api/blogs
Accept: application/json
Content-Type: application/json

{
    "title": "River campeón",
    "author": "Marcelo Daniel Gallardo",
    "url": "www.river.com.ar",
    "likes": 912
}